add_executable(logger_example logger_example.cpp)
target_link_libraries(logger_example PRIVATE SoulCoreKit)
windeployqt_post_build(logger_example FALSE)

add_executable(network_example network_example.cpp)
target_link_libraries(network_example PRIVATE SoulCoreKit)
windeployqt_post_build(network_example FALSE)

add_executable(soulcore_demo main.cpp)
target_link_libraries(soulcore_demo PRIVATE SoulCoreKit)
windeployqt_post_build(soulcore_demo FALSE)

add_executable(full_stack_example full_stack_example.cpp)
target_link_libraries(full_stack_example PRIVATE SoulCoreKit)
windeployqt_post_build(full_stack_example FALSE)

add_executable(simple_test simple_test.cpp)
target_link_libraries(simple_test PRIVATE soul_core)